image: node:14.5.0

stages:
  - build
  - staging
  - deploy

build_angular:
  stage: build
  script:
    - npm install
    - npm run docker
  artifacts:
    paths:
      - ./docker

build_image:
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  image: docker:20.10
  services:
    - docker:20.10-dind
  stage: staging
  only: [tags]
  script:
    - docker build -t spotify-stats:$CI_COMMIT_TAG docker
  needs:
    - job: build_angular
      artifacts: true
