image: kojenka/spotify-stats-runner:latest

stages:
  - build
  - deploy

build_angular:
  stage: build
  script:
    - npm install
    - npm run docker

build_image:
  stage: build
  only: [tags]
  script:
    - docker build -t spotify-stats:$CI_COMMIT_TAG docker
