image: node:14.5.0

stages:
  - build
  - deploy

build_angular:
  stage: build
  script:
    - npm install
    - npm run docker
  artifacts:
    paths:
      - ./docker

build_image:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  image: docker:20.10
  services:
    - docker:20.10-dind
  only: [tags]
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - echo "===== BUILD IMAGE ====="
    - docker build -t kojenka/spotify-stats:$CI_COMMIT_TAG docker
    - docker tag kojenka/spotify-stats:$CI_COMMIT_TAG kojenka/spotify-stats:latest
    - echo "===== PUSH IMAGE ====="
    - docker push kojenka/spotify-stats:$CI_COMMIT_TAG
    - docker push kojenka/spotify-stats:latest
  needs:
    - job: build_angular
      artifacts: true
